apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # pods represented by this service
  selector:
    app: queue
  ports:
    - name: http
      # service own port
      port: 8161
      # externally exposed port
      nodePort: 30010
    - name: endpoint
      # service own port
      port: 61616
  # it's an exposed service (otherwise ClusterIP)
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  # crucial, mandatory name
  name: fleetman-position-tracker
spec:
  # pods represented by this service
  selector:
    app: position-tracker
  ports:
    - name: http
      # service own port
      port: 8080
  # it's a non-exposed service (otherwise NodePort)
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  # crucial, mandatory name
  name: fleetman-api-gateway
spec:
  # pods represented by this service
  selector:
    app: api-gateway
  ports:
    - name: http
      # service own port
      port: 8080
      # externally exposed port
      nodePort: 30020
  # it's an exposed service (otherwise ClusterIP)
  type: NodePort
