apiVersion: v1
kind: Service
metadata:
  name: fleetman-service
spec:
  # pods represented by this service
  selector:
    app: fleetman-queue
    release: "1"
  ports:
    - name: http
      # service own port
      port: 8161
      # pod own port
      # targetPort: 8161
      # externally exposed port
      nodePort: 30010
  # it's an exposed service (otherwise ClusterIP)
  type: NodePort
