apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # pods represented by this service
  selector:
    app: webapp
  ports:
    - name: http
      # service own port
      port: 80
      # pod own port
      # targetPort: 80
      # externally exposed port
      nodePort: 30080
  # it's an exposed service (otherwise ClusterIP)
  type: NodePort
